/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.14.3/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "kern"

include("kern-commons")
include("kern-struct")
include("kern-dependency")
include("kern-dependency:api")
include("kern-dependency:simple")
include("kern-dependency:versioned")
include("kern-meta")
include("kern-meta:core")
include("kern-meta:apt")
include("kern-memory")
